#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/nick/network-sim/mptcp/arch/sim/test/buildtop/build/lib
 export PATH=$PATH:/home/nick/network-sim/mptcp/arch/sim/test/buildtop/build/bin
 export PYTHONPATH=$PYTHONPATH:/home/nick/network-sim/mptcp/arch/sim/test/bake:/home/nick/network-sim/mptcp/arch/sim/test/buildtop/build/lib:/home/nick/network-sim/mptcp/arch/sim/test/buildtop/build/lib/python2.7/dist-packages
 export INSTALL_BASE=/home/nick/network-sim/mptcp/arch/sim/test/buildtop/build
