# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('nicholson-nc-udp', ['core'])
    module.source = [
        'model/nicholson-nc-udp-encoder-agent.cc',
        'model/nicholson-nc-udp-decoder-agent.cc',
        'model/nicholson-nc-udp-router-agent.cc',
        'model/timer-handler.cc',
        'model/network_coding/Galois_Field.cc',
        'model/network_coding/Matrix.cc',
        'model/network_coding/Test_Manual.cc',
        ]

    module_test = bld.create_ns3_module_test_library('nicholson-nc-udp')
    module_test.source = [
        'test/nicholson-nc-udp-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'nicholson-nc-udp'
    headers.source = [
        'model/nicholson-nc-udp-encoder-agent.h',
        'model/nicholson-nc-udp-decoder-agent.h',
        'model/nicholson-nc-udp-router-agent.h',
        'model/agent.h',
        'model/app.h',
        'model/ip.h',
        'model/random.h',
        'model/tcp.h',
        'model/udp.h',
        'model/rtp.h',
        'model/packet.h',
        'model/timer-handler.h',
        'helper/nicholson-nc-udp-helper.h',
        'model/network_coding/Galois_Field.h',
        'model/network_coding/Matrix.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

